version: '3.0'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sakila
      MYSQL_DATABASE: sakila
      MYSQL_PASSWORD: sakila
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./sakila-db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
  
 
